# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Nix"
license = "MIT"
licenselink = "https://github.com/LordMathis/hugo-theme-nix/blob/master/LICENSE.md"
description = "Simple theme for Hugo"
homepage = "https://github.com/LordMathis/hugo-theme-nix/"
tags = ["simple", "minimal", "unix", "terminal", "blog"]
features = ["blog"]
min_version = 0.15

[author]
  name = "Matúš Námešný"
  homepage = "https://namesny.com"

